name: Daily Cron Job

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend cron
        run: |
          curl -X GET "${{ secrets.CRON_API_URL }}"
