name: Daily Cron Job

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: # optional: lets you run manually from Actions tab

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend cron
        run: |
          curl -X GET "${{ secrets.CRON_API_URL }}"
